function rezMaxM = on_compare_dual_label( ...
  barcodeGen, ...
  theoryStruct, ...
  numPixelsAroundBestTheoryMask, ...
  sets, ...
  externalAlignmentStruct)

% Change to balance precision/speed
digits(32) % Number of digits precision.
pThresh = 0; % Minimum value of 1-p to calculate score.
zThresh = 0;%norminv(pThresh);

% load theory barcode txt file.
formatSpec = '%f';
fileID = fopen(theoryStruct.filename,'r');
theorBar1 = transpose(fscanf(fileID,formatSpec));
fclose(fileID);
fileID = fopen(theoryStruct.filename2,'r');
theorBar2 = transpose(fscanf(fileID,formatSpec));
fclose(fileID);
try
  fileID = fopen(strrep(theoryStruct.filename, 'barcode', 'bitmask'),'r');
  theorBit = transpose(fscanf(fileID,formatSpec));
  fclose(fileID);
catch
  theorBit = ones(size(theorBar1));
end

% Load zero-model params
theoryNumPixels = 3088286401/sets.pvalue.pixelWidth_nm*sets.pvalue.nmbp;
numStretchFactors = length(sets.theory.stretchFactors);
import CBT.Hca.Import.load_pval_struct;
cbParamsPath = fullfile(sets.pvalue.paramFolder, "cb_zero_model_params.txt");
dotsParamsPath = fullfile(sets.pvalue.paramFolder, ...
  compose("dots_%s_zero_model_params.txt", sets.pvalue.pattern));
[cbPsfInd, cbParams] = load_pval_struct(cbParamsPath);
[dotsPsfInd, dotParams] = load_pval_struct(dotsParamsPath);
psfPxRounded = round(sets.pvalue.psfSigmaWidth_nm/sets.pvalue.pixelWidth_nm, 4);
try
  cbParamLambda = cbParams{ismember(psfPxRounded, cbPsfInd)}(1);
  cbParamExa = cbParams{ismember(psfPxRounded, cbPsfInd)}(2);
  cbParamNu = cbParams{ismember(psfPxRounded, cbPsfInd)}(3);
catch
  error(compose("Zero-model params for psf: %.2f not found in file: %s", ...
    psfPxRounded, cbParamsPath));
end
try
  dotParamLambda = dotParams{ismember(psfPxRounded, dotsPsfInd)}(1);
  dotParamExa = dotParams{ismember(psfPxRounded, dotsPsfInd)}(2);
  dotParamMu = dotParams{ismember(psfPxRounded, dotsPsfInd)}(3);
  dotParamXi = dotParams{ismember(psfPxRounded, dotsPsfInd)}(4);
  dotParamSigma = dotParams{ismember(psfPxRounded, dotsPsfInd)}(5);
catch
  error(compose("Zero-model params for psf: %.2f not found in file: %s", ...
    psfPxRounded, dotsParamsPath));
end

rezMaxM = cell(1, size(barcodeGen, 2));
barcodeGenDense = barcodeGen(1, :);
barcodeGenSparse = barcodeGen(2, :);
% for all the barcodes run
for idx=1:size(barcodeGen, 2)
  
  % scoreMax stores the  maximum coefficients
  scoreMax = zeros(4,length(sets.theory.stretchFactors));
  
  % rezMaz stores the results for one barcode
  rezMaxDual = cell(1,length(sets.theory.stretchFactors));
  rezMaxDense = cell(1,length(sets.theory.stretchFactors));
  rezMaxSparse = cell(1,length(sets.theory.stretchFactors));
  rezMaxExternal = cell(1,length(sets.theory.stretchFactors));
  
  % length of this barcode
  lenBarTested = length(barcodeGenDense{idx}.rawBarcode);
  
  % run the loop for the stretch factors
  for j=1:length(sets.theory.stretchFactors)
    % here interpolate both barcode and bitmask
    lenBarStretched = round(lenBarTested*sets.theory.stretchFactors(j));
    v = linspace(1, lenBarTested, lenBarStretched);
    barDense = interp1(barcodeGenDense{idx}.rawBarcode, v);
    barSparse = interp1(barcodeGenSparse{idx}.rawBarcode, v);
    
    import DL.Hca.beta_ev_cdf
    xDense = MASS_PCC( ...
      theorBar1, ...
      barDense, ...
      2^(4+nextpow2(lenBarStretched)));
    zDense = zThresh*ones(size(xDense));
    lambdaEffDense = cbParamLambda*cbParamExa*numStretchFactors*(theoryNumPixels-lenBarStretched);
    xThreshDense = norminv(pThresh^(1/lambdaEffDense), 0, nanstd(xDense(:)));
    doZScore = xDense > xThreshDense;
    zDense(doZScore) = -sqrt(2)*erfcinv(2*beta_ev_cdf( ...
      xDense(doZScore), ...
      max(4, cbParamNu*lenBarStretched), ...
      1, ...
      lambdaEffDense));
    doIncreasedPrecision = isinf(zDense) & zDense > 0;
    zDense(doIncreasedPrecision) = -sqrt(2)*erfcinv(2*beta_ev_cdf( ...
      xDense(doIncreasedPrecision), ...
      max(4, cbParamNu*lenBarStretched), ...
      1, ...
      lambdaEffDense, ...
      true));
    
    import DL.Hca.trunc_normal_ev_cdf
    xSparse = MASS_DOT_CC( ...
      theorBar2, ...
      barSparse, ...
      2^(4+nextpow2(lenBarStretched)));
    zSparse = zThresh*ones(size(xSparse));
    lambdaEffSparse = dotParamLambda*dotParamExa*numStretchFactors*(theoryNumPixels-lenBarStretched);
    xThreshSparse = norminv(pThresh^(1/lambdaEffSparse), dotParamMu, nanstd(xSparse(:)));
    doZScore = xSparse > xThreshSparse;
    zSparse(doZScore) = -sqrt(2)*erfcinv(2*trunc_normal_ev_cdf( ...
      xSparse(doZScore), ...
      norminv(linspace(0.001, 0.999, 31), ...
      dotParamMu, ...
      1/sqrt(dotParamXi*lenBarStretched)), ...
      1/sqrt(dotParamSigma*lenBarStretched), ...
      lambdaEffSparse, ...
      0, 1));
    doIncreasedPrecision = isinf(zSparse) & zSparse > 0;
    zSparse(doIncreasedPrecision) = -sqrt(2)*erfcinv(2*trunc_normal_ev_cdf( ...
      xSparse(doIncreasedPrecision), ...
      norminv(linspace(0.001, 0.999, 51),  ...
      dotParamMu, ...
      1/sqrt(dotParamXi*lenBarStretched)), ...
      1/sqrt(dotParamSigma*lenBarStretched), ...
      lambdaEffSparse, ...
      0, 1, true));
    
    import CBT.Hca.UI.Helper.get_best_parameters;
    [rezMaxDual{j}.maxcoef, ...
      rezMaxDual{j}.pos, ...
      rezMaxDual{j}.or] = get_best_parameters((zDense + zSparse)/sqrt(2), ...
      3, lenBarStretched, 1, numPixelsAroundBestTheoryMask, ...
      theorBit);
    [rezMaxDense{j}.maxcoef, ...
      rezMaxDense{j}.pos, ...
      rezMaxDense{j}.or] = get_best_parameters(zDense, ...
      3, lenBarStretched, 1, numPixelsAroundBestTheoryMask, ...
      theorBit);
    [rezMaxSparse{j}.maxcoef, ...
      rezMaxSparse{j}.pos, ...
      rezMaxSparse{j}.or] = get_best_parameters(zSparse, ...
      3, lenBarStretched, 1, numPixelsAroundBestTheoryMask, ...
      theorBit);
    
    rezMaxDual{j}.maxcoefParts = [ ...
      arrayfun(@(i) zDense(rezMaxDual{j}.or(i), rezMaxDual{j}.pos(i)), 1:3); ...
      arrayfun(@(i) zSparse(rezMaxDual{j}.or(i), rezMaxDual{j}.pos(i)), 1:3)];
    rezMaxDual{j}.maxcoefPartsCC = [ ...
      arrayfun(@(i) xDense(rezMaxDual{j}.or(i), rezMaxDual{j}.pos(i)), 1:3); ...
      arrayfun(@(i) xSparse(rezMaxDual{j}.or(i), rezMaxDual{j}.pos(i)), 1:3)];
    rezMaxDense{j}.maxcoefParts = [ ...
      arrayfun(@(i) zDense(rezMaxDense{j}.or(i), rezMaxDense{j}.pos(i)), 1:3); ...
      arrayfun(@(i) zSparse(rezMaxDense{j}.or(i), rezMaxDense{j}.pos(i)), 1:3)];
    rezMaxDense{j}.maxcoefPartsCC = [ ...
      arrayfun(@(i) xDense(rezMaxDense{j}.or(i), rezMaxDense{j}.pos(i)), 1:3); ...
      arrayfun(@(i) xSparse(rezMaxDense{j}.or(i), rezMaxDense{j}.pos(i)), 1:3)];
    rezMaxSparse{j}.maxcoefParts = [ ...
      arrayfun(@(i) zDense(rezMaxSparse{j}.or(i), rezMaxSparse{j}.pos(i)), 1:3); ...
      arrayfun(@(i) zSparse(rezMaxSparse{j}.or(i), rezMaxSparse{j}.pos(i)), 1:3)];
    rezMaxSparse{j}.maxcoefPartsCC = [ ...
      arrayfun(@(i) xDense(rezMaxSparse{j}.or(i), rezMaxSparse{j}.pos(i)), 1:3); ...
      arrayfun(@(i) xSparse(rezMaxSparse{j}.or(i), rezMaxSparse{j}.pos(i)), 1:3)];
    
    scoreMax(1, j) = rezMaxDual{j}.maxcoef(1);
    scoreMax(2, j) = rezMaxDense{j}.maxcoef(1);
    scoreMax(3, j) = rezMaxSparse{j}.maxcoef(1);
    
    if nargin > 4
      rezMaxExternal{j}.pos = externalAlignmentStruct.pos(idx);
      rezMaxExternal{j}.or = externalAlignmentStruct.or(idx);
      rezMaxExternal{j}.maxcoef = (zDense(rezMaxExternal{j}.or, rezMaxExternal{j}.pos) ...
        + zSparse(rezMaxExternal{j}.or, rezMaxExternal{j}.pos))/sqrt(2);
      rezMaxExternal{j}.maxcoefParts = [ ...
        zDense(rezMaxExternal{j}.or, rezMaxExternal{j}.pos); ...
        zSparse(rezMaxExternal{j}.or, rezMaxExternal{j}.pos)];
      rezMaxExternal{j}.maxcoefPartsCC = [ ...
        xDense(rezMaxExternal{j}.or, rezMaxExternal{j}.pos); ...
        xSparse(rezMaxExternal{j}.or, rezMaxExternal{j}.pos)];
      scoreMax(4, j) = rezMaxExternal{j}.maxcoefParts(2);
    else
      rezMaxExternal{j}.maxcoef = nan;
    end
  end
  
  [~,b] = nanmax(scoreMax(1,:));
  [~,c] = nanmax(scoreMax(2,:));
  [~,d] = nanmax(scoreMax(3,:));
  [~,e] = nanmax(scoreMax(4,:));
  rezMaxM{idx}.dual = rezMaxDual{b};
  rezMaxM{idx}.dual.bestBarStretch = sets.theory.stretchFactors(b);
  rezMaxM{idx}.dual.bestLength = round(lenBarTested*sets.theory.stretchFactors(b));
  rezMaxM{idx}.dense = rezMaxDense{c};
  rezMaxM{idx}.dense.bestBarStretch = sets.theory.stretchFactors(c);
  rezMaxM{idx}.dense.bestLength = round(lenBarTested*sets.theory.stretchFactors(c));
  rezMaxM{idx}.sparse = rezMaxSparse{d};
  rezMaxM{idx}.sparse.bestBarStretch = sets.theory.stretchFactors(d);
  rezMaxM{idx}.sparse.bestLength = round(lenBarTested*sets.theory.stretchFactors(d));
  rezMaxM{idx}.external = rezMaxExternal{e};
  rezMaxM{idx}.external.bestBarStretch = sets.theory.stretchFactors(e);
  rezMaxM{idx}.external.bestLength = round(lenBarTested*sets.theory.stretchFactors(e));
  if nargin > 4
    disp(num2str([idx rezMaxM{idx}.dual.maxcoef(1) rezMaxM{idx}.dense.maxcoef(1) rezMaxM{idx}.sparse.maxcoef(1) rezMaxM{idx}.external.maxcoef rezMaxM{idx}.external.maxcoefParts']))
  else
    disp(num2str([idx rezMaxM{idx}.dual.maxcoef(1) rezMaxM{idx}.dense.maxcoef(1) rezMaxM{idx}.sparse.maxcoef(1)]))
  end
end
